Repository Codeit-T5/FE_Codeit_T5, pull requests merged in 2025-02, with the labels that each got.

#57 Dev/younha
  public/images/mypage/conversation-icon.svg
  public/images/mypage/heart.svg
  public/images/mypage/open-book.svg
  src/apis/axiosInstance.ts
  src/apis/login.ts
  src/apis/myMoim.ts
  src/apis/ownMoim.ts
  src/apis/participatedMoim.ts
  src/apis/reviews.ts
  src/apis/userInfo.ts
  src/app/mypage/editUser/page.tsx
  src/app/mypage/page.tsx
  src/components/filter/Filter.tsx
  src/components/filter/filterTabs/Tabs.tsx
  src/components/mypage/ComingSoon.tsx
  src/components/mypage/CreatedMeetings.tsx
  src/components/mypage/Meetings.tsx
  src/components/mypage/filterBar/DropDown.tsx
  src/components/mypage/filterBar/FilterBar.tsx
  src/components/mypage/filterBar/SwitchFilter.tsx
  src/components/mypage/filterBar/switch/switch.tsx
  src/components/mypage/gatheringCard/GatheringCard.tsx
  src/components/mypage/myReview/CreateReview.tsx
  src/components/mypage/myprofile/MyProfile.tsx
  src/components/mypage/renderTab/RenderTab.tsx
  src/containers/mypage/TemporaryLogin.tsx
  src/hooks/mypage/queries/useMoimsQuery.ts
  src/hooks/mypage/queries/useUserQuery.ts
  src/hooks/mypage/useUserFormData.ts
  src/types/mypage/moim.type.ts
  src/types/mypage/reviews.type.ts
  src/types/mypage/user.ts
  src/types/supabase/supabase.ts
  src/utils/mypage/statusTags.ts
Labels: Feat-develop

#77 Dev/dohee 유저 인증 관련 오류 수정
  src/apis/detail/axios.api.ts
  src/apis/detail/detail.api.ts
  src/components/detail/ChipSmallSquircle.tsx
  src/components/detail/DetailInfo.tsx
  src/components/detail/DetailPresenter.tsx
  src/components/mylike/MyLikeCard.tsx
  src/components/mylike/MyLikeCards.tsx
  src/components/mylike/MyLikePresenter.tsx
  src/containers/mylike/MyLikeContainer.tsx
Labels: Feat-develop

#79 Dev/younha
  public/images/dudu_logo_animation.json
  public/images/mypage/camera.svg
  src/app/layout.tsx
  src/app/mypage/editUser/page.tsx
  src/app/mypage/review/[gatheringId]/page.tsx
  src/components/filter/Filter.tsx
  src/components/filter/filterTabs/FilterTabs.tsx
  src/components/filter/filterTabs/Tabs.tsx
  src/components/home/HomeCard.tsx
  src/components/home/HomeHero.tsx
  src/components/mypage/ComingSoon.tsx
  src/components/mypage/CreatedMeetings.tsx
  src/components/mypage/LoadingAnimation.tsx
  src/components/mypage/Meetings.tsx
  src/components/mypage/UserEdit.tsx
  src/components/mypage/edit/UserEditForm.tsx
  src/components/mypage/filterBar/DropDown.tsx
  src/components/mypage/filterBar/FilterBar.tsx
  src/components/mypage/gatheringCard/GatheringCard.tsx
  src/components/mypage/header/Header.tsx
  src/components/mypage/myReview/CompletedReview.tsx
  src/components/mypage/myReview/CreateReview.tsx
  src/components/mypage/myReview/MyReviewContainer.tsx
  src/components/mypage/myReview/PendingReview.tsx
  src/components/mypage/myReview/ReviewCard.tsx
  src/components/mypage/myReview/ReviewTabs.tsx
  src/components/mypage/myprofile/MyProfile.tsx
  src/components/mypage/renderTab/RenderTab.tsx
  src/hooks/home/useCreateMoim.ts
  src/stores/home/likeStore.ts
  src/types/mypage/moim.type.ts
  src/types/mypage/reviews.type.ts
  src/types/mypage/user.ts
  src/types/supabase/supabase.ts
  src/utils/home/fetchMoims.ts
  src/utils/mypage/statusTags.ts
  tailwind.config.ts
Labels: Feat-develop

#85 Dev/dohee
  src/apis/detail/detail.api.ts
  src/components/detail/ChipSmallSquircle.tsx
  src/components/detail/DetailPresenter.tsx
  src/components/detail/FloatingBar.tsx
  src/components/detail/join/JoinButton.tsx
  src/components/mylike/MyLikeCard.tsx
  src/containers/detail/DetailContainer.tsx
  src/hooks/detail/useJoinMoim.ts
  src/types/detail/i-components.ts
  src/types/detail/i-presenter.ts
Labels: Feat-develop

#93 Dev/younha
  src/apis/moimLikey.ts
  src/apis/reviews.ts
  src/app/api/auth/me/route.ts
  src/app/api/moims/liked/route.ts
  src/app/mypage/review/[gatheringId]/page.tsx
  src/components/mypage/CreatedMeetings.tsx
  src/components/mypage/Meetings.tsx
  src/components/mypage/UserEdit.tsx
  src/components/mypage/gatheringCard/GatheringCard.tsx
  src/components/mypage/myReview/CreateReview.tsx
  src/hooks/mypage/queries/useLikeyQuery.ts
  src/hooks/mypage/queries/useReviewQuery.ts
  src/hooks/mypage/queries/useUserQuery.ts
  src/types/mypage/moim.type.ts
  src/types/mypage/reviews.type.ts
  src/utils/mypage/statusTags.ts
Labels: Feat-develop

#103 Dev/younha
  public/images/mypage/visibility_off.svg
  public/images/mypage/visibility_on.svg
  src/apis/userInfo.ts
  src/app/mypage/editPassword/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/review/[gatheringId]/page.tsx
  src/components/ComingSoon.tsx
  src/components/mypage/CreatedMeetings.tsx
  src/components/mypage/EditPassword.tsx
  src/components/mypage/LoadingAnimation.tsx
  src/components/mypage/Meetings.tsx
  src/components/mypage/UserEdit.tsx
  src/components/mypage/filterBar/DropDown.tsx
  src/components/mypage/filterBar/FilterBar.tsx
  src/components/mypage/filterBar/SwitchFilter.tsx
  src/components/mypage/gatheringCard/GatheringCard.tsx
  src/components/mypage/header/Header.tsx
  src/components/mypage/myReview/CompletedReview.tsx
  src/components/mypage/myReview/CreateReview.tsx
  src/components/mypage/myReview/PendingReview.tsx
  src/components/mypage/myReview/ReviewCard.tsx
  src/components/mypage/myReview/ReviewTabs.tsx
  src/components/mypage/myprofile/MyProfile.tsx
  src/components/mypage/renderTab/RenderTab.tsx
  src/hooks/mypage/queries/useLikeyQuery.ts
  src/hooks/mypage/queries/useMoimsQuery.ts
  src/hooks/mypage/queries/useReviewQuery.ts
  src/types/mypage/moim.type.ts
  src/types/mypage/reviews.type.ts
  src/types/mypage/user.ts
  src/utils/mypage/statusTags.ts
Labels: Feat-develop

#105 Dev/dohee
  src/apis/detail/detail.api.ts
  src/app/detail/[id]/page.tsx
  src/app/layout.tsx
  src/app/mylike/page.tsx
  src/components/detail/ChipSmallSquircle.tsx
  src/components/detail/DetailHost.tsx
  src/components/detail/DetailInfo.tsx
  src/components/detail/DetailParticipants.tsx
  src/components/detail/DetailPresenter.tsx
  src/components/detail/DetailShare.tsx
  src/components/detail/DetailSkeleton.tsx
  src/components/detail/FloatingBar.tsx
  src/components/detail/ParticipantsList.tsx
  src/components/detail/ToasterDark.tsx
  src/components/detail/join/JoinButton.tsx
  src/components/mylike/MyLikeCard.tsx
  src/components/mylike/MyLikePresenter.tsx
  src/components/mylike/MyLikeSkeleton.tsx
  src/containers/detail/DetailContainer.tsx
  src/containers/mylike/MyLikeContainer.tsx
  src/hooks/detail/useJoinMoim.ts
  src/hooks/detail/useLikeMoim.ts
  src/hooks/detail/useMoimDetail.ts
  src/hooks/mylike/useLikedMoims.ts
  src/types/detail/i-components.ts
  src/types/detail/i-presenter.ts
  src/types/detail/t-moim.ts
  src/utils/detail/enums.ts
Labels: Feat-develop

#117 Dev/younha
  src/apis/userInfo.ts
  src/components/common/ComingSoon.tsx
  src/components/common/TagInput.tsx
  src/components/home/HomeCard.tsx
  src/components/home/HomeCards.tsx
  src/components/home/HomeGnb.tsx
  src/components/home/HomeHeaderDesk.tsx
  src/components/mylike/MyLikePresenter.tsx
  src/components/mylike/MyLikeSkeleton.tsx
  src/components/mypage/CreatedMeetings.tsx
  src/components/mypage/EditPassword.tsx
  src/components/mypage/Meetings.tsx
  src/components/mypage/UserEdit.tsx
  src/components/mypage/edit/UserEditForm.tsx
  src/components/mypage/gatheringCard/GatheringCard.tsx
  src/components/mypage/header/Header.tsx
  src/components/mypage/myReview/CompletedReview.tsx
  src/components/mypage/myReview/CreateReview.tsx
  src/components/mypage/myReview/PendingReview.tsx
  src/components/mypage/myprofile/MyProfile.tsx
  src/components/mypage/renderTab/RenderTab.tsx
  src/containers/detail/DetailContainer.tsx
  src/containers/mylike/MyLikeContainer.tsx
  src/containers/mypage/MypageContainer.tsx
  src/hooks/detail/useLikeMoim.ts
  src/hooks/detail/useMoimDetail.ts
  src/hooks/mypage/useUserFormData.ts
  src/libs/home/home-axios.ts
  src/types/mypage/user.ts
  src/utils/mypage/statusTags.ts
Labels: Style-develop

#121 Dev/younha
  src/components/mypage/UserEdit.tsx
  src/types/mypage/user.ts
Labels: 버그
